#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: retrieval-ingress
#  namespace: t24-data-retrieval-service
#spec:
#  rules:
#  - host: retrieval.com
#    http:
#      paths:
#      - pathType: Prefix
#        path: "/"
#        backend:
#          service:
#            name: t24-data-retrieval-service
#            port:
#              number: 8080
